version: '2'

volumes:
  ghost_blog: {}

services:
  ghost:
    image: ghost
    volumes:
      - ghost_blog:/var/lib/ghost
    ports:
     - "2368:2368"
    restart: always

  buster:
    image: raccoony/buster
    links:
      - ghost
    depends_on:
      - ghost
    env_file: .env
    environment:
      - PUBLIC_URL=${GITHUB_ID}.github.io
      - GIT_REPO=git@github.com:${GITHUB_ID}/${GITHUB_ID}.github.io.git
    volumes:
      - ${SSH_KEY}:/root/.ssh/id_rsa
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
    ports:
      - "9000:9000"
